import { ConfigService } from '@nestjs/config';
import { DashboardEvaluationService } from '../evaluations/dashboard-evaluation.service';
import { DsaEvaluationService } from '../evaluations/dsa-evaluation.service';
import { McqEvaluationService } from '../evaluations/mcq-evaluation.service';
import { OopsEvaluationService } from '../evaluations/oops-evaluation.service';
import { SqlEvaluationService } from '../evaluations/sql-evaluation.service';
import { QuestionBankService } from '../question-bank/question-bank.service';
export declare class AssessmentPipelineService {
    private readonly config;
    private readonly questionBank;
    private readonly dsaEvaluation;
    private readonly sqlEvaluation;
    private readonly oopsEvaluation;
    private readonly mcqEvaluation;
    private readonly dashboardEvaluation;
    private supabase?;
    constructor(config: ConfigService, questionBank: QuestionBankService, dsaEvaluation: DsaEvaluationService, sqlEvaluation: SqlEvaluationService, oopsEvaluation: OopsEvaluationService, mcqEvaluation: McqEvaluationService, dashboardEvaluation: DashboardEvaluationService);
    finalize(rawInput: unknown): Promise<{
        attempt_id: string;
        report_id: unknown;
        report: Record<string, unknown>;
        dashboard_evaluation: import("../ai/ai.types").JsonObject;
    }>;
    private parseInput;
    private evaluateCodingSection;
    private evaluateSqlSection;
    private evaluateMcqSection;
    private tryEvaluate;
    private persistAttempt;
    private persistQuestionAttempts;
    private persistEvaluations;
    private persistFinalRuntimeSnapshots;
    private persistFinalCodeRuns;
    private persistFinalSqlRuns;
    private persistFinalMcqAnswers;
    private parseTestSummary;
    private persistReport;
    private fallbackQuestionEvaluation;
    private fallbackDashboard;
    private getSupabase;
    private sameStringSet;
    private average;
    private computeReadiness;
    private trainingPriority;
    private teacherAction;
    private numberOutput;
    private riskOutput;
    private compilationOutput;
    private bucketFromReadinessLabel;
    private companyRecommendation;
    private trainingRecommendation;
    private stringArrayOutput;
    private uuidOrNull;
    private questionStatus;
    private strongestArea;
    private weakestArea;
}
